import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import { FaGithub } from "react-icons/fa";
import { FaHouse } from "react-icons/fa6";
import DarkModeButton from "@/components/dark-mode-button/DarkModeButton";
import LanguageSelect from "@/components/language-select/LanguageSelect";
import Image from "next/image";
import RoundButton from "@/components/round-button/RoundButton";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.gnb}>
          <div className={styles.gnbContents}>
            <div className={styles.logo}>
              <FaHouse size="24" />
              JAEMIN KIM
            </div>
            <div className={styles.toolbar}>
              <RoundButton>
                {/* <FontAwesomeIcon icon={FaGithub} /> */}
                <FaGithub size="16" />
                {/* <Image */}
                {/*   src="github-mark.svg" */}
                {/*   alt="github" */}
                {/*   width="16" */}
                {/*   height="16" */}
                {/* /> */}
              </RoundButton>
              <LanguageSelect />
              <DarkModeButton />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
